# Generated by Django 2.0 on 2019-09-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='admin_teacherNo',
            field=models.CharField(max_length=20, verbose_name='教师工号'),
        ),
    ]
