# Generated by Django 2.0 on 2019-09-04 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190904_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='admin_teacherNo',
        ),
    ]
