# Generated by Django 2.2.5 on 2019-09-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_userprofile_admin_teacherno'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='admin_teacherNo',
            field=models.CharField(default='', max_length=20, verbose_name='工号'),
        ),
    ]
