# Generated by Django 2.2.5 on 2019-09-07 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_admin_teacherno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='admin_rank',
            field=models.CharField(choices=[('普通老师', '普通老师'), ('学院领导', '学院领导'), ('教务处老师', '教务处老师')], max_length=7, verbose_name='用户等级'),
        ),
    ]
