# Generated by Django 2.0 on 2019-09-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20190630_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkformhc',
            name='class_name',
            field=models.CharField(default='', max_length=20, verbose_name='实验班级名称'),
        ),
        migrations.AddField(
            model_name='checkformhc',
            name='course_name',
            field=models.CharField(default='', max_length=20, verbose_name='所属课程名称'),
        ),
        migrations.AddField(
            model_name='checkformhc',
            name='experiment_name',
            field=models.CharField(default='', max_length=20, verbose_name='实验课程名称'),
        ),
        migrations.AddField(
            model_name='checkformhc',
            name='experiment_number',
            field=models.CharField(default='', max_length=20, verbose_name='实验人数'),
        ),
        migrations.AlterField(
            model_name='checkformhc',
            name='admin',
            field=models.CharField(max_length=10, verbose_name='二级审核者'),
        ),
        migrations.AlterField(
            model_name='checkformhc',
            name='creator',
            field=models.CharField(max_length=10, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='checkformhc',
            name='data_company',
            field=models.CharField(max_length=10, verbose_name='单位'),
        ),
        migrations.AlterField(
            model_name='checkformhc',
            name='data_count',
            field=models.CharField(max_length=10, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='checkformhc',
            name='data_person',
            field=models.CharField(max_length=10, verbose_name='验收领用人'),
        ),
        migrations.AlterField(
            model_name='checkformhc',
            name='data_price',
            field=models.CharField(max_length=10, verbose_name='单价'),
        ),
        migrations.AlterField(
            model_name='checkformhc',
            name='data_price2',
            field=models.CharField(max_length=10, verbose_name='金额'),
        ),
        migrations.AlterField(
            model_name='checkformhc',
            name='data_usedate',
            field=models.CharField(max_length=20, verbose_name='使用日期'),
        ),
        migrations.AlterField(
            model_name='checkformhc',
            name='date',
            field=models.CharField(max_length=20, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='checkformhc',
            name='examine',
            field=models.CharField(max_length=10, verbose_name='一级审核者'),
        ),
        migrations.AlterField(
            model_name='checkformhc',
            name='term',
            field=models.CharField(max_length=10, verbose_name='学期'),
        ),
        migrations.AlterField(
            model_name='checkformyq',
            name='admin',
            field=models.CharField(max_length=10, verbose_name='二级审核者'),
        ),
        migrations.AlterField(
            model_name='checkformyq',
            name='creator',
            field=models.CharField(max_length=10, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='checkformyq',
            name='data_company',
            field=models.CharField(max_length=10, verbose_name='单位'),
        ),
        migrations.AlterField(
            model_name='checkformyq',
            name='data_company2',
            field=models.CharField(max_length=10, verbose_name='使用单位'),
        ),
        migrations.AlterField(
            model_name='checkformyq',
            name='data_count',
            field=models.CharField(max_length=10, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='checkformyq',
            name='data_parameter',
            field=models.TextField(verbose_name='规格及技术参数'),
        ),
        migrations.AlterField(
            model_name='checkformyq',
            name='data_price',
            field=models.CharField(max_length=10, verbose_name='预算单价'),
        ),
        migrations.AlterField(
            model_name='checkformyq',
            name='data_price2',
            field=models.CharField(max_length=10, verbose_name='预算金额'),
        ),
        migrations.AlterField(
            model_name='checkformyq',
            name='date',
            field=models.CharField(max_length=20, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='checkformyq',
            name='examine',
            field=models.CharField(max_length=10, verbose_name='一级审核者'),
        ),
        migrations.AlterField(
            model_name='checkformyq',
            name='term',
            field=models.CharField(max_length=20, verbose_name='学期'),
        ),
    ]
