# Generated by Django 2.2.5 on 2019-09-07 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20190904_2018'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminForm',
        ),
    ]
